[2025-05-21T12:44:20.647+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T11:44:14.984546+00:00 [queued]>
[2025-05-21T12:44:20.668+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T11:44:14.984546+00:00 [queued]>
[2025-05-21T12:44:20.669+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T12:44:20.693+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 11:44:14.984546+00:00
[2025-05-21T12:44:20.698+0000] {standard_task_runner.py:57} INFO - Started process 191 to run task
[2025-05-21T12:44:20.702+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'scheduled__2025-05-21T11:44:14.984546+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpe5nnq3id']
[2025-05-21T12:44:20.705+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask process_weather_data
[2025-05-21T12:44:20.728+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T12:44:20.790+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T11:44:14.984546+00:00 [running]> on host 00732dad519c
[2025-05-21T12:44:20.979+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T11:44:14.984546+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T11:44:14.984546+00:00'
[2025-05-21T12:44:20.987+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T12:44:20.990+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T12:44:21.003+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T12:44:21.020+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T12:44:28.379+0000] {subprocess.py:93} INFO - 25/05/21 12:44:28 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T12:44:29.050+0000] {subprocess.py:93} INFO - 25/05/21 12:44:29 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T12:44:29.052+0000] {subprocess.py:93} INFO - 25/05/21 12:44:29 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T12:44:29.053+0000] {subprocess.py:93} INFO - 25/05/21 12:44:29 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T12:44:31.033+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T12:44:31.133+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO ResourceUtils: ==============================================================
[2025-05-21T12:44:31.140+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T12:44:31.143+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO ResourceUtils: ==============================================================
[2025-05-21T12:44:31.144+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T12:44:31.232+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T12:44:31.255+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T12:44:31.260+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T12:44:31.412+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T12:44:31.418+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T12:44:31.427+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T12:44:31.435+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T12:44:31.439+0000] {subprocess.py:93} INFO - 25/05/21 12:44:31 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T12:44:32.491+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO Utils: Successfully started service 'sparkDriver' on port 39827.
[2025-05-21T12:44:32.594+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T12:44:32.707+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T12:44:32.795+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T12:44:32.796+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T12:44:32.803+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T12:44:32.852+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-1bc1c8fd-96c9-42db-a18f-f20f8d6f86da
[2025-05-21T12:44:32.880+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T12:44:32.942+0000] {subprocess.py:93} INFO - 25/05/21 12:44:32 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T12:44:33.716+0000] {subprocess.py:93} INFO - 25/05/21 12:44:33 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T12:44:33.836+0000] {subprocess.py:93} INFO - 25/05/21 12:44:33 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T12:44:33.853+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T12:44:33.859+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T12:44:33.864+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T12:44:33.870+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T12:44:33.871+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T12:44:33.871+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T12:44:33.872+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T12:44:33.872+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T12:44:33.873+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T12:44:33.873+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T12:44:33.874+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T12:44:33.875+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T12:44:33.876+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T12:44:33.877+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T12:44:33.878+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T12:44:33.879+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T12:44:33.879+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T12:44:33.879+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T12:44:33.880+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T12:44:33.882+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T12:44:33.888+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T12:44:33.891+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T12:44:34.105+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T12:44:34.213+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 59 ms (0 ms spent in bootstraps)
[2025-05-21T12:44:34.510+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521124434-0000
[2025-05-21T12:44:34.525+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 32903.
[2025-05-21T12:44:34.526+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO NettyBlockTransferService: Server created on 00732dad519c:32903
[2025-05-21T12:44:34.531+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T12:44:34.551+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 00732dad519c, 32903, None)
[2025-05-21T12:44:34.558+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO BlockManagerMasterEndpoint: Registering block manager 00732dad519c:32903 with 434.4 MiB RAM, BlockManagerId(driver, 00732dad519c, 32903, None)
[2025-05-21T12:44:34.564+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 00732dad519c, 32903, None)
[2025-05-21T12:44:34.566+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 00732dad519c, 32903, None)
[2025-05-21T12:44:34.589+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521124434-0000/0 on worker-20250521124403-172.18.0.6-44149 (172.18.0.6:44149) with 2 core(s)
[2025-05-21T12:44:34.593+0000] {subprocess.py:93} INFO - 25/05/21 12:44:34 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521124434-0000/0 on hostPort 172.18.0.6:44149 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T12:44:35.075+0000] {subprocess.py:93} INFO - 25/05/21 12:44:35 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521124434-0000/0 is now RUNNING
[2025-05-21T12:44:35.370+0000] {subprocess.py:93} INFO - 25/05/21 12:44:35 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T12:44:36.110+0000] {subprocess.py:93} INFO - 2025-05-21 12:44:36,110 - INFO - Processing weather data from MinIO
[2025-05-21T12:44:36.124+0000] {subprocess.py:93} INFO - 25/05/21 12:44:36 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T12:44:36.130+0000] {subprocess.py:93} INFO - 25/05/21 12:44:36 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpeuu0pbn1/spark-warehouse'.
[2025-05-21T12:44:39.018+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T12:44:39.021+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:39.022+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T12:44:39.032+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T12:44:39.032+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T12:44:39.033+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T12:44:39.033+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T12:44:39.034+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T12:44:39.034+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T12:44:39.035+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T12:44:39.036+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T12:44:39.036+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T12:44:39.037+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T12:44:39.045+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T12:44:39.048+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T12:44:39.055+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T12:44:39.061+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T12:44:39.066+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T12:44:39.073+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T12:44:39.086+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T12:44:39.095+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T12:44:39.097+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T12:44:39.105+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T12:44:39.107+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T12:44:39.111+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T12:44:39.113+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T12:44:39.113+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T12:44:39.114+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T12:44:39.114+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T12:44:39.115+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:39.115+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T12:44:39.116+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T12:44:39.116+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T12:44:39.184+0000] {subprocess.py:93} INFO - 2025-05-21 12:44:39,183 - ERROR - Weather data processing failed: An error occurred while calling o35.json.
[2025-05-21T12:44:39.188+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:39.190+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T12:44:39.192+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T12:44:39.193+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T12:44:39.194+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T12:44:39.195+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T12:44:39.196+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T12:44:39.196+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T12:44:39.197+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T12:44:39.197+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T12:44:39.198+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T12:44:39.199+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T12:44:39.200+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T12:44:39.200+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T12:44:39.201+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T12:44:39.202+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T12:44:39.202+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T12:44:39.203+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T12:44:39.204+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T12:44:39.206+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T12:44:39.209+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T12:44:39.211+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T12:44:39.211+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T12:44:39.217+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T12:44:39.218+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T12:44:39.218+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T12:44:39.222+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T12:44:39.224+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T12:44:39.225+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T12:44:39.233+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T12:44:39.234+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T12:44:39.236+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:39.238+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T12:44:39.240+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T12:44:39.246+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T12:44:39.271+0000] {subprocess.py:93} INFO - 
[2025-05-21T12:44:39.313+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO SparkUI: Stopped Spark web UI at http://00732dad519c:4040
[2025-05-21T12:44:39.329+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T12:44:39.347+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T12:44:39.406+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T12:44:39.558+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO MemoryStore: MemoryStore cleared
[2025-05-21T12:44:39.570+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO BlockManager: BlockManager stopped
[2025-05-21T12:44:39.580+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T12:44:39.583+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T12:44:39.611+0000] {subprocess.py:93} INFO - 25/05/21 12:44:39 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T12:44:40.064+0000] {subprocess.py:93} INFO - 25/05/21 12:44:40 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T12:44:40.065+0000] {subprocess.py:93} INFO - 25/05/21 12:44:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-1026cf8a-52af-4e59-96de-b17241aaa7d9
[2025-05-21T12:44:40.071+0000] {subprocess.py:93} INFO - 25/05/21 12:44:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-14809790-662f-4c35-9932-efe88c0519e8
[2025-05-21T12:44:40.085+0000] {subprocess.py:93} INFO - 25/05/21 12:44:40 INFO ShutdownHookManager: Deleting directory /tmp/spark-14809790-662f-4c35-9932-efe88c0519e8/pyspark-7675e680-137e-4629-9edc-13afbd56f8dd
[2025-05-21T12:44:40.166+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T12:44:40.231+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T114414, start_date=20250521T124420, end_date=20250521T124440
[2025-05-21T12:44:40.287+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T12:44:40.335+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
