[2025-05-20T20:28:49.002+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yellow_taxi_batch_pipeline.transform_taxi_data manual__2025-05-20T20:28:02.179623+00:00 [queued]>
[2025-05-20T20:28:49.012+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yellow_taxi_batch_pipeline.transform_taxi_data manual__2025-05-20T20:28:02.179623+00:00 [queued]>
[2025-05-20T20:28:49.013+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-20T20:28:49.028+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): transform_taxi_data> on 2025-05-20 20:28:02.179623+00:00
[2025-05-20T20:28:49.033+0000] {standard_task_runner.py:57} INFO - Started process 386 to run task
[2025-05-20T20:28:49.036+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'yellow_taxi_batch_pipeline', 'transform_taxi_data', 'manual__2025-05-20T20:28:02.179623+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/taxi_batch_dag.py', '--cfg-path', '/tmp/tmpx2rl3vdb']
[2025-05-20T20:28:49.039+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask transform_taxi_data
[2025-05-20T20:28:49.062+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T20:28:49.113+0000] {task_command.py:415} INFO - Running <TaskInstance: yellow_taxi_batch_pipeline.transform_taxi_data manual__2025-05-20T20:28:02.179623+00:00 [running]> on host b54dcde9a5b4
[2025-05-20T20:28:49.217+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='yellow_taxi_batch_pipeline' AIRFLOW_CTX_TASK_ID='transform_taxi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T20:28:02.179623+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T20:28:02.179623+00:00'
[2025-05-20T20:28:49.219+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T20:28:49.220+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar         --packages org.apache.hadoop:hadoop-aws:3.3.1         /opt/airflow/dags/scripts/taxi_transform.py\n    ']
[2025-05-20T20:28:49.230+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T20:28:49.235+0000] {subprocess.py:93} INFO - /bin/bash: line 2: spark-submit: command not found
[2025-05-20T20:28:49.236+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-05-20T20:28:49.250+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-05-20T20:28:49.256+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=yellow_taxi_batch_pipeline, task_id=transform_taxi_data, execution_date=20250520T202802, start_date=20250520T202849, end_date=20250520T202849
[2025-05-20T20:28:49.270+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 36 for task transform_taxi_data (Bash command failed. The command returned a non-zero exit code 127.; 386)
[2025-05-20T20:28:49.289+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-20T20:28:49.311+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
