[2025-05-21T09:27:33.046+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:27:22.833952+00:00 [queued]>
[2025-05-21T09:27:33.092+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:27:22.833952+00:00 [queued]>
[2025-05-21T09:27:33.096+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T09:27:33.138+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 09:27:22.833952+00:00
[2025-05-21T09:27:33.149+0000] {standard_task_runner.py:57} INFO - Started process 286 to run task
[2025-05-21T09:27:33.153+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'manual__2025-05-21T09:27:22.833952+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmpeigb0gec']
[2025-05-21T09:27:33.162+0000] {standard_task_runner.py:85} INFO - Job 61: Subtask process_weather_data
[2025-05-21T09:27:33.186+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T09:27:33.253+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data manual__2025-05-21T09:27:22.833952+00:00 [running]> on host c4c55d29c79f
[2025-05-21T09:27:33.371+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T09:27:22.833952+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T09:27:22.833952+00:00'
[2025-05-21T09:27:33.373+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T09:27:33.374+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar         --packages org.apache.hadoop:hadoop-aws:3.3.1         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T09:27:33.385+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T09:27:33.394+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T09:27:36.430+0000] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-05-21T09:27:36.688+0000] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/airflow/.ivy2/cache
[2025-05-21T09:27:36.689+0000] {subprocess.py:93} INFO - The jars for the packages stored in: /home/airflow/.ivy2/jars
[2025-05-21T09:27:36.704+0000] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2025-05-21T09:27:36.706+0000] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-28194eac-547c-46db-893a-92899861d369;1.0
[2025-05-21T09:27:36.707+0000] {subprocess.py:93} INFO - 	confs: [default]
[2025-05-21T09:27:37.149+0000] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.1 in central
[2025-05-21T09:27:37.208+0000] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.11.901 in central
[2025-05-21T09:27:37.259+0000] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2025-05-21T09:27:38.228+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar ...
[2025-05-21T09:27:39.179+0000] {subprocess.py:93} INFO - 	[SUCCESSFUL ] org.apache.hadoop#hadoop-aws;3.3.1!hadoop-aws.jar (1893ms)
[2025-05-21T09:27:39.249+0000] {subprocess.py:93} INFO - downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar ...
[2025-05-21T09:28:29.133+0000] {subprocess.py:93} INFO - :: resolution report :: resolve 576ms :: artifacts dl 51851ms
[2025-05-21T09:28:29.136+0000] {subprocess.py:93} INFO - 	:: modules in use:
[2025-05-21T09:28:29.137+0000] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.11.901 from central in [default]
[2025-05-21T09:28:29.139+0000] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.1 from central in [default]
[2025-05-21T09:28:29.140+0000] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2025-05-21T09:28:29.140+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:28:29.141+0000] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2025-05-21T09:28:29.143+0000] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2025-05-21T09:28:29.144+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:28:29.144+0000] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   1   |
[2025-05-21T09:28:29.145+0000] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2025-05-21T09:28:29.146+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.147+0000] {subprocess.py:93} INFO - :: problems summary ::
[2025-05-21T09:28:29.148+0000] {subprocess.py:93} INFO - :::: WARNINGS
[2025-05-21T09:28:29.149+0000] {subprocess.py:93} INFO - 		[FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.11.901!aws-java-sdk-bundle.jar: Downloaded file size (0) doesn't match expected Content Length (192321266) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar. Please retry. (49944ms)
[2025-05-21T09:28:29.150+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.150+0000] {subprocess.py:93} INFO - 		[FAILED     ] com.amazonaws#aws-java-sdk-bundle;1.11.901!aws-java-sdk-bundle.jar: Downloaded file size (0) doesn't match expected Content Length (192321266) for https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar. Please retry. (49944ms)
[2025-05-21T09:28:29.151+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.151+0000] {subprocess.py:93} INFO - 	==== central: tried
[2025-05-21T09:28:29.152+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.152+0000] {subprocess.py:93} INFO - 	  https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar
[2025-05-21T09:28:29.153+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.154+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-21T09:28:29.154+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.155+0000] {subprocess.py:93} INFO - 		::              FAILED DOWNLOADS            ::
[2025-05-21T09:28:29.157+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.165+0000] {subprocess.py:93} INFO - 		:: ^ see resolution messages for details  ^ ::
[2025-05-21T09:28:29.165+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.167+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-21T09:28:29.168+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.168+0000] {subprocess.py:93} INFO - 		:: com.amazonaws#aws-java-sdk-bundle;1.11.901!aws-java-sdk-bundle.jar
[2025-05-21T09:28:29.169+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.169+0000] {subprocess.py:93} INFO - 		::::::::::::::::::::::::::::::::::::::::::::::
[2025-05-21T09:28:29.170+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.171+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.172+0000] {subprocess.py:93} INFO - 
[2025-05-21T09:28:29.172+0000] {subprocess.py:93} INFO - :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
[2025-05-21T09:28:29.173+0000] {subprocess.py:93} INFO - Exception in thread "main" java.lang.RuntimeException: [download failed: com.amazonaws#aws-java-sdk-bundle;1.11.901!aws-java-sdk-bundle.jar]
[2025-05-21T09:28:29.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1456)
[2025-05-21T09:28:29.174+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
[2025-05-21T09:28:29.175+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
[2025-05-21T09:28:29.175+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:901)
[2025-05-21T09:28:29.177+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
[2025-05-21T09:28:29.177+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
[2025-05-21T09:28:29.178+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
[2025-05-21T09:28:29.179+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1046)
[2025-05-21T09:28:29.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1055)
[2025-05-21T09:28:29.180+0000] {subprocess.py:93} INFO - 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-05-21T09:28:29.182+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-21T09:28:29.212+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-21T09:28:29.220+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T092722, start_date=20250521T092733, end_date=20250521T092829
[2025-05-21T09:28:29.301+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 61 for task process_weather_data (Bash command failed. The command returned a non-zero exit code 1.; 286)
[2025-05-21T09:28:29.341+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-05-21T09:28:29.384+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
