[2025-05-21T12:44:44.975+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T11:44:41.288178+00:00 [queued]>
[2025-05-21T12:44:44.983+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T11:44:41.288178+00:00 [queued]>
[2025-05-21T12:44:44.984+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-05-21T12:44:44.996+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): process_weather_data> on 2025-05-21 11:44:41.288178+00:00
[2025-05-21T12:44:45.000+0000] {standard_task_runner.py:57} INFO - Started process 533 to run task
[2025-05-21T12:44:45.003+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'weather_streaming_pipeline', 'process_weather_data', 'scheduled__2025-05-21T11:44:41.288178+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/weather_streaming_dag.py', '--cfg-path', '/tmp/tmp5sa64xis']
[2025-05-21T12:44:45.005+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask process_weather_data
[2025-05-21T12:44:45.022+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-21T12:44:45.059+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_streaming_pipeline.process_weather_data scheduled__2025-05-21T11:44:41.288178+00:00 [running]> on host 00732dad519c
[2025-05-21T12:44:45.139+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_streaming_pipeline' AIRFLOW_CTX_TASK_ID='process_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T11:44:41.288178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T11:44:41.288178+00:00'
[2025-05-21T12:44:45.142+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-21T12:44:45.143+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n    spark-submit         --master spark://spark-master:7077         --jars /opt/airflow/dags/jars/***ql-42.5.0.jar,/opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar,/opt/airflow/dags/jars/hadoop-aws-3.3.1.jar         /opt/airflow/dags/scripts/weather_transform.py\n    ']
[2025-05-21T12:44:45.152+0000] {subprocess.py:86} INFO - Output:
[2025-05-21T12:44:45.160+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-05-21T12:44:47.273+0000] {subprocess.py:93} INFO - 25/05/21 12:44:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-05-21T12:44:47.477+0000] {subprocess.py:93} INFO - 25/05/21 12:44:47 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/***ql-42.5.0.jar does not exist, skipping.
[2025-05-21T12:44:47.478+0000] {subprocess.py:93} INFO - 25/05/21 12:44:47 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/aws-java-sdk-bundle-1.11.901.jar does not exist, skipping.
[2025-05-21T12:44:47.478+0000] {subprocess.py:93} INFO - 25/05/21 12:44:47 WARN DependencyUtils: Local jar /opt/airflow/dags/jars/hadoop-aws-3.3.1.jar does not exist, skipping.
[2025-05-21T12:44:48.707+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SparkContext: Running Spark version 3.3.1
[2025-05-21T12:44:48.737+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO ResourceUtils: ==============================================================
[2025-05-21T12:44:48.738+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-05-21T12:44:48.739+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO ResourceUtils: ==============================================================
[2025-05-21T12:44:48.739+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SparkContext: Submitted application: WeatherTransform
[2025-05-21T12:44:48.760+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-05-21T12:44:48.773+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO ResourceProfile: Limiting resource is cpu
[2025-05-21T12:44:48.774+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-05-21T12:44:48.823+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SecurityManager: Changing view acls to: airflow
[2025-05-21T12:44:48.824+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SecurityManager: Changing modify acls to: airflow
[2025-05-21T12:44:48.825+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SecurityManager: Changing view acls groups to:
[2025-05-21T12:44:48.825+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SecurityManager: Changing modify acls groups to:
[2025-05-21T12:44:48.826+0000] {subprocess.py:93} INFO - 25/05/21 12:44:48 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
[2025-05-21T12:44:49.103+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO Utils: Successfully started service 'sparkDriver' on port 42007.
[2025-05-21T12:44:49.143+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO SparkEnv: Registering MapOutputTracker
[2025-05-21T12:44:49.192+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO SparkEnv: Registering BlockManagerMaster
[2025-05-21T12:44:49.216+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-05-21T12:44:49.217+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-05-21T12:44:49.222+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-05-21T12:44:49.248+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-e26b6d5a-f901-4786-a217-458ad69584f6
[2025-05-21T12:44:49.270+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-05-21T12:44:49.293+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-05-21T12:44:49.603+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-05-21T12:44:49.650+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 ERROR SparkContext: Failed to add /opt/spark/jars/***ql-42.5.0.jar to Spark environment
[2025-05-21T12:44:49.651+0000] {subprocess.py:93} INFO - java.io.FileNotFoundException: Jar /opt/spark/jars/***ql-42.5.0.jar not found
[2025-05-21T12:44:49.651+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addLocalJarFile$1(SparkContext.scala:1949)
[2025-05-21T12:44:49.652+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.addJar(SparkContext.scala:2004)
[2025-05-21T12:44:49.652+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12(SparkContext.scala:507)
[2025-05-21T12:44:49.653+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.$anonfun$new$12$adapted(SparkContext.scala:507)
[2025-05-21T12:44:49.653+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2025-05-21T12:44:49.653+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2025-05-21T12:44:49.654+0000] {subprocess.py:93} INFO - 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2025-05-21T12:44:49.654+0000] {subprocess.py:93} INFO - 	at org.apache.spark.SparkContext.<init>(SparkContext.scala:507)
[2025-05-21T12:44:49.655+0000] {subprocess.py:93} INFO - 	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
[2025-05-21T12:44:49.655+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-05-21T12:44:49.656+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2025-05-21T12:44:49.656+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-05-21T12:44:49.657+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[2025-05-21T12:44:49.657+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
[2025-05-21T12:44:49.657+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T12:44:49.658+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:238)
[2025-05-21T12:44:49.658+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
[2025-05-21T12:44:49.659+0000] {subprocess.py:93} INFO - 	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
[2025-05-21T12:44:49.659+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T12:44:49.660+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T12:44:49.660+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T12:44:49.787+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-05-21T12:44:49.852+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 43 ms (0 ms spent in bootstraps)
[2025-05-21T12:44:49.989+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250521124449-0002
[2025-05-21T12:44:49.992+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250521124449-0002/0 on worker-20250521124403-172.18.0.6-44149 (172.18.0.6:44149) with 2 core(s)
[2025-05-21T12:44:49.996+0000] {subprocess.py:93} INFO - 25/05/21 12:44:49 INFO StandaloneSchedulerBackend: Granted executor ID app-20250521124449-0002/0 on hostPort 172.18.0.6:44149 with 2 core(s), 1024.0 MiB RAM
[2025-05-21T12:44:50.000+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34195.
[2025-05-21T12:44:50.001+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO NettyBlockTransferService: Server created on 00732dad519c:34195
[2025-05-21T12:44:50.003+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-05-21T12:44:50.014+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 00732dad519c, 34195, None)
[2025-05-21T12:44:50.020+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO BlockManagerMasterEndpoint: Registering block manager 00732dad519c:34195 with 434.4 MiB RAM, BlockManagerId(driver, 00732dad519c, 34195, None)
[2025-05-21T12:44:50.024+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 00732dad519c, 34195, None)
[2025-05-21T12:44:50.026+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 00732dad519c, 34195, None)
[2025-05-21T12:44:50.059+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250521124449-0002/0 is now RUNNING
[2025-05-21T12:44:50.341+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-05-21T12:44:50.569+0000] {subprocess.py:93} INFO - 2025-05-21 12:44:50,569 - INFO - Processing weather data from MinIO
[2025-05-21T12:44:50.575+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-05-21T12:44:50.578+0000] {subprocess.py:93} INFO - 25/05/21 12:44:50 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpi9moy_8j/spark-warehouse'.
[2025-05-21T12:44:51.693+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi-data/weather/*.json.
[2025-05-21T12:44:51.694+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:51.694+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T12:44:51.695+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T12:44:51.695+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T12:44:51.696+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T12:44:51.696+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T12:44:51.697+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T12:44:51.697+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T12:44:51.698+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T12:44:51.698+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-05-21T12:44:51.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:370)
[2025-05-21T12:44:51.699+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T12:44:51.700+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T12:44:51.700+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T12:44:51.701+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T12:44:51.702+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T12:44:51.702+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T12:44:51.703+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T12:44:51.703+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T12:44:51.704+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T12:44:51.704+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T12:44:51.705+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T12:44:51.706+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T12:44:51.707+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T12:44:51.707+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T12:44:51.710+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T12:44:51.711+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T12:44:51.711+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T12:44:51.712+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:51.713+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T12:44:51.713+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T12:44:51.715+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-05-21T12:44:51.760+0000] {subprocess.py:93} INFO - 2025-05-21 12:44:51,760 - ERROR - Weather data processing failed: An error occurred while calling o35.json.
[2025-05-21T12:44:51.761+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:51.762+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-05-21T12:44:51.762+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-05-21T12:44:51.763+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-05-21T12:44:51.763+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-05-21T12:44:51.764+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-05-21T12:44:51.764+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-05-21T12:44:51.765+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-05-21T12:44:51.765+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-05-21T12:44:51.765+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:752)
[2025-05-21T12:44:51.766+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-05-21T12:44:51.766+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:750)
[2025-05-21T12:44:51.767+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:579)
[2025-05-21T12:44:51.767+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:408)
[2025-05-21T12:44:51.768+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:228)
[2025-05-21T12:44:51.768+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:210)
[2025-05-21T12:44:51.769+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-05-21T12:44:51.769+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:210)
[2025-05-21T12:44:51.769+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:361)
[2025-05-21T12:44:51.770+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-05-21T12:44:51.770+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-05-21T12:44:51.771+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-05-21T12:44:51.771+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2025-05-21T12:44:51.772+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-05-21T12:44:51.772+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
[2025-05-21T12:44:51.772+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-05-21T12:44:51.773+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-05-21T12:44:51.773+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-05-21T12:44:51.774+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-05-21T12:44:51.774+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-05-21T12:44:51.775+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-21T12:44:51.775+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-05-21T12:44:51.776+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-05-21T12:44:51.777+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-05-21T12:44:51.777+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-05-21T12:44:51.778+0000] {subprocess.py:93} INFO - 
[2025-05-21T12:44:51.779+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO SparkUI: Stopped Spark web UI at http://00732dad519c:4040
[2025-05-21T12:44:51.784+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-05-21T12:44:51.791+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
[2025-05-21T12:44:51.820+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-05-21T12:44:51.839+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO MemoryStore: MemoryStore cleared
[2025-05-21T12:44:51.840+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO BlockManager: BlockManager stopped
[2025-05-21T12:44:51.848+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-05-21T12:44:51.851+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-05-21T12:44:51.860+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO SparkContext: Successfully stopped SparkContext
[2025-05-21T12:44:51.920+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO ShutdownHookManager: Shutdown hook called
[2025-05-21T12:44:51.921+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-bd242cfd-ec55-4368-af3c-30683da9142a
[2025-05-21T12:44:51.925+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-bd242cfd-ec55-4368-af3c-30683da9142a/pyspark-405872b3-1d94-4ec9-a740-b96a089117aa
[2025-05-21T12:44:51.929+0000] {subprocess.py:93} INFO - 25/05/21 12:44:51 INFO ShutdownHookManager: Deleting directory /tmp/spark-700b5225-f27e-49f6-8ec5-f2e60d7829ed
[2025-05-21T12:44:51.986+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-21T12:44:52.029+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=weather_streaming_pipeline, task_id=process_weather_data, execution_date=20250521T114441, start_date=20250521T124444, end_date=20250521T124452
[2025-05-21T12:44:52.059+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T12:44:52.077+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
